version: '3'

services:
  api:
    image: nvcr.io/nvidia/pytorch:23.12-py3
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GPU_ENABLED=true
      - USE_TENSORRT=true
      - TENSORRT_PRECISION=fp16
      - LOG_LEVEL=DEBUG
      - ENABLE_CORS=true
    volumes:
      - ./app.py:/app/app.py
    working_dir: /app
    runtime: nvidia
    command: bash -c "pip install fastapi uvicorn pydantic && python -m uvicorn app:app --host 0.0.0.0 --port 8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]