version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
      - ./cache:/app/cache
    environment:
      - TEST_MODE=true
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
