version: '3.8'

name: sap-hana-langchain-frontend

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: sap-hana-langchain/frontend:latest
    container_name: sap-hana-langchain-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=${BACKEND_URL:-http://localhost:8000}
      - VITE_APP_VERSION=${APP_VERSION:-1.0.0}
      - VITE_ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}
    volumes:
      - ./frontend/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped