version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.ngc
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - tensorrt_cache:/app/tensorrt_cache
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GPU_ENABLED=true
      - USE_TENSORRT=true
      - TENSORRT_PRECISION=fp16
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  tensorrt_cache: