version: '3.8'

services:
  api:
    build: 
      context: api
      dockerfile: Dockerfile.local
    ports:
      - "8000:8000"
    environment:
      - HANA_HOST=${HANA_HOST:-localhost}
      - HANA_PORT=${HANA_PORT:-30015}
      - HANA_USER=${HANA_USER:-SYSTEM}
      - HANA_PASSWORD=${HANA_PASSWORD:-password}
      - PORT=8000
      - LOG_LEVEL=INFO
      - ENABLE_CORS=true
      - CORS_ORIGINS=*
      - TEST_MODE=true
      - ENABLE_ERROR_CONTEXT=true
      - ERROR_DETAIL_LEVEL=verbose
      - INCLUDE_SUGGESTIONS=true
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - MULTI_GPU_ENABLED=false
      - USE_TENSORRT=false
    restart: unless-stopped