version: '3'

services:
  api:
    image: python:3.9
    ports:
      - "8000:8000"
    volumes:
      - ./test_app.py:/app/test_app.py
    working_dir: /app
    command: bash -c "pip install fastapi uvicorn && python -m uvicorn test_app:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s