version: '3.8'

services:
  api:
    build: .
    image: local-sap-hana-api:latest
    ports:
      - "8000:8000"
    environment:
      - TEST_MODE=true
      - ENABLE_CORS=true
      - LOG_LEVEL=INFO
    restart: unless-stopped