version: '3.8'

name: sap-hana-langchain-ngc-blueprint

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.nvidia
      args:
        BASE_IMAGE: nvcr.io/nvidia/pytorch:23.12-py3
    image: nvcr.io/nvidia/sap-enhanced/langchain-hana-gpu:latest
    container_name: sap-hana-langchain-api-nvidia
    ports:
      - "8000:8000"
    environment:
      # SAP HANA Cloud Connection
      - HANA_HOST=${HANA_HOST}
      - HANA_PORT=${HANA_PORT:-443}
      - HANA_USER=${HANA_USER}
      - HANA_PASSWORD=${HANA_PASSWORD}
      - DEFAULT_TABLE_NAME=${DEFAULT_TABLE_NAME:-EMBEDDINGS}
      
      # GPU Acceleration (optimized for NGC)
      - GPU_ENABLED=true
      - USE_TENSORRT=true
      - TENSORRT_PRECISION=${TENSORRT_PRECISION:-fp16}
      - TENSORRT_ENGINE_CACHE_DIR=/app/trt_engines
      - BATCH_SIZE=${BATCH_SIZE:-64}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-256}
      - ENABLE_MULTI_GPU=true
      
      # API and Error Settings
      - ENABLE_CORS=true
      - JWT_SECRET=${JWT_SECRET:-sap-hana-langchain-integration-secret-key}
      - ENABLE_CONTEXT_AWARE_ERRORS=true
      - LOG_LEVEL=INFO
    volumes:
      - nvidia-trt-engines:/app/trt_engines
      - nvidia-data:/app/data
      - nvidia-logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "test_app_enhanced:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

volumes:
  nvidia-trt-engines:
    driver: local
  nvidia-data:
    driver: local
  nvidia-logs:
    driver: local