#!/bin/bash

# Script to move relevant files to the new directory structure

# Create necessary directories
mkdir -p backend/api
mkdir -p backend/data
mkdir -p backend/logs
mkdir -p backend/config

# Copy API files to backend
echo "Copying API files to backend/api..."
cp -r api/* backend/api/ 2>/dev/null || :

# Copy langchain_hana files
echo "Copying langchain_hana files..."
cp -r langchain_hana backend/ 2>/dev/null || :

# Copy requirements and version files
echo "Copying requirements and version files..."
cp requirements.txt backend/ 2>/dev/null || :
cp VERSION backend/ 2>/dev/null || :

# Create simple README files for directories
echo "Creating README files for directories..."
echo "# Backend Data Directory\n\nThis directory stores persistent data for the backend." > backend/data/README.md
echo "# Backend Logs Directory\n\nThis directory stores logs generated by the backend." > backend/logs/README.md
echo "# Backend Configuration Directory\n\nThis directory contains configuration files for the backend." > backend/config/README.md

# Create .gitkeep files to ensure empty directories are tracked
touch backend/data/.gitkeep
touch backend/logs/.gitkeep

echo "File structure setup complete!"