global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8000']
    metrics_path: /health/metrics

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']