version: '3.8'

name: sap-hana-langchain-nvidia

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nvidia
      args:
        BASE_IMAGE: nvcr.io/nvidia/pytorch:23.12-py3
    image: langchain-hana-nvidia:latest
    container_name: sap-hana-langchain-api-nvidia
    ports:
      - "8000:8000"
    environment:
      # SAP HANA Cloud Connection
      - HANA_HOST=${HANA_HOST}
      - HANA_PORT=${HANA_PORT:-443}
      - HANA_USER=${HANA_USER}
      - HANA_PASSWORD=${HANA_PASSWORD}
      - DEFAULT_TABLE_NAME=${DEFAULT_TABLE_NAME:-EMBEDDINGS}
      
      # API Configuration
      - PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_CORS=${ENABLE_CORS:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - JWT_SECRET=${JWT_SECRET:-sap-hana-langchain-integration-secret-key}
      - DB_MAX_CONNECTIONS=${DB_MAX_CONNECTIONS:-5}
      - DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT:-600}
      
      # GPU Acceleration
      - GPU_ENABLED=true
      - USE_TENSORRT=true
      - TENSORRT_PRECISION=${TENSORRT_PRECISION:-fp16}
      - TENSORRT_ENGINE_CACHE_DIR=/app/trt_engines
      - BATCH_SIZE=${BATCH_SIZE:-32}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-128}
      - ENABLE_MULTI_GPU=${ENABLE_MULTI_GPU:-true}
      - GPU_MEMORY_FRACTION=${GPU_MEMORY_FRACTION:-0.9}
      
      # Error Handling
      - ENABLE_CONTEXT_AWARE_ERRORS=${ENABLE_CONTEXT_AWARE_ERRORS:-true}
      - ERROR_VERBOSITY=${ERROR_VERBOSITY:-standard}
      - ENABLE_ERROR_TELEMETRY=${ENABLE_ERROR_TELEMETRY:-true}
      
      # Vector Operations
      - ENABLE_PRECISE_SIMILARITY=${ENABLE_PRECISE_SIMILARITY:-true}
      - DEFAULT_EMBEDDING_MODEL=${DEFAULT_EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - ENABLE_VECTOR_VISUALIZATION=${ENABLE_VECTOR_VISUALIZATION:-true}
    volumes:
      - nvidia-trt-engines:/app/trt_engines
      - nvidia-api-data:/app/data
      - nvidia-api-logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: ["python", "-m", "uvicorn", "api.core.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    image: langchain-hana-frontend:latest
    container_name: sap-hana-langchain-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://api:8000
      - VITE_APP_VERSION=${APP_VERSION:-1.0.0}
      - VITE_ENABLE_VECTOR_VISUALIZATION=true
      - VITE_ENABLE_DARK_MODE=true
      - VITE_ENABLE_ACCESSIBILITY=true
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  nvidia-trt-engines:
    driver: local
  nvidia-api-data:
    driver: local
  nvidia-api-logs:
    driver: local