apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-hana-api
  namespace: langchain-hana-production
  labels:
    app: langchain-hana-api
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: langchain-hana-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: langchain-hana-api
        environment: production
    spec:
      containers:
      - name: langchain-hana-api
        image: ghcr.io/sap/langchain-integration-for-sap-hana-cloud/backend:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            memory: "8Gi"
            cpu: "2"
        envFrom:
        - configMapRef:
            name: langchain-hana-config
        - secretRef:
            name: langchain-hana-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health/startup
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
      nodeSelector:
        accelerator: nvidia-gpu