# CI/CD Configuration for GPU Acceleration Module
# This file documents the CI/CD requirements for this module

version: 1.0.0

# Testing requirements
testing:
  # Unit tests for components
  unit_tests:
    - path: tests/unit_tests/test_hana_tensorrt_components.py
    - path: tests/unit_tests/test_batch_processor.py
    - path: tests/unit_tests/test_batch_processor_extended.py
  
  # Integration tests
  integration_tests:
    - path: tests/test_tensorrt_t4.py
  
  # Test requirements
  requirements:
    - python: ">=3.8,<4.0"
    - torch: ">=2.0.0"
    - tensorrt: ">=8.0.0"
    - pytest: ">=7.0.0"
    - pytest-cov: ">=4.0.0"

# Quality checks
quality:
  # Linting
  linters:
    - black:
        line-length: 100
    - flake8:
        max-line-length: 100
        ignore:
          - E203  # Whitespace before ':'
          - W503  # Line break before binary operator
    - isort:
        profile: black
    - mypy:
        python_version: 3.8
        disallow_untyped_defs: true
        disallow_incomplete_defs: true
  
  # Documentation
  docs:
    - check-docstrings
    - validate-examples
  
  # Type checking
  type_checking:
    - mypy
    - pylance

# Security checks
security:
  # Static Application Security Testing (SAST)
  sast:
    - bandit
    - semgrep
  
  # Dependency scanning
  dependency_scan:
    - safety
    - pip-audit

# Performance benchmarks
benchmarks:
  # TensorRT performance
  tensorrt:
    - benchmark_precision_modes:
        models:
          - "sentence-transformers/all-MiniLM-L6-v2"
          - "sentence-transformers/all-mpnet-base-v2"
        precisions:
          - fp32
          - fp16
          - int8
        batch_sizes:
          - 1
          - 16
          - 64
          - 256
  
  # SAP HANA vector operations
  vectorstore:
    - benchmark_add_texts:
        doc_counts:
          - 100
          - 1000
          - 10000
    - benchmark_search:
        k_values:
          - 5
          - 50
          - 100

# Release management
release:
  version_pattern: "X.Y.Z"
  changelog: CHANGELOG.md
  triggers:
    - tag: "v*"
    - branch: main

# Deployment requirements
deployment:
  # Base image for Docker
  docker:
    base_image: "nvcr.io/nvidia/pytorch:23.03-py3"
    cuda_version: "11.8"
    tensorrt_version: "8.5.3"
  
  # GPU requirements
  gpu:
    minimum:
      type: "NVIDIA T4"
      memory: "8GB"
    recommended:
      type: "NVIDIA T4"
      memory: "16GB"
  
  # Resource requirements
  resources:
    cpu:
      minimum: "4 vCPUs"
      recommended: "8+ vCPUs"
    memory:
      minimum: "16GB RAM"
      recommended: "32GB+ RAM"

# Documentation requirements
documentation:
  user_guide: "/docs/gpu_acceleration.md"
  example_code: "/examples/hana_gpu_acceleration.py"
  api_reference: "/docs/api/reference.md"

# Monitoring requirements
monitoring:
  metrics:
    - embedding_generation_time
    - throughput_docs_per_second
    - memory_usage
    - gpu_utilization
  prometheus:
    enabled: true
    endpoint: "/metrics"

# Compliance
compliance:
  - pep8
  - type-hinting
  - docstring-coverage
  - test-coverage:
      minimum: 80%