version: '3'

services:
  api:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - GPU_ENABLED=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]