name: Arrow Flight Integration CI

on:
  push:
    branches: [ main ]
    paths:
      - 'langchain_hana/gpu/arrow_flight_*.py'
      - 'langchain_hana/gpu/arrow_gpu_memory_manager.py'
      - 'api/routes/flight.py'
      - 'benchmarks/arrow_flight_benchmark.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'langchain_hana/gpu/arrow_flight_*.py'
      - 'langchain_hana/gpu/arrow_gpu_memory_manager.py'
      - 'api/routes/flight.py'
      - 'benchmarks/arrow_flight_benchmark.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install pyarrow
        pip install -e .
    
    - name: Unit tests
      run: |
        pytest tests/unit_tests/test_arrow_flight_components.py -v --cov=langchain_hana.gpu
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install pyarrow
        pip install -e .
    
    - name: Set up mock SAP HANA
      run: |
        docker pull saplabs/hanaexpress:latest
        docker run -d --name hana-mock -p 39017:39017 saplabs/hanaexpress:latest
        python tests/setup_hana_tables.py
    
    - name: Integration tests
      run: |
        pytest tests/integration_tests/test_arrow_flight_integration.py -v
    
    - name: Run benchmarks
      run: |
        python benchmarks/arrow_flight_benchmark.py --host localhost --port 39017 --user SYSTEM --password manager --num-documents 1000 --skip-multi-gpu
    
    - name: Archive benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: benchmark_results/

  gpu-benchmark:
    runs-on: [self-hosted, gpu]
    needs: integration-test
    if: github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install pyarrow torch
        pip install -e .
    
    - name: Set up mock SAP HANA
      run: |
        docker pull saplabs/hanaexpress:latest
        docker run -d --name hana-mock-gpu -p 39017:39017 saplabs/hanaexpress:latest
        python tests/setup_hana_tables.py
    
    - name: Run full benchmarks with GPU
      run: |
        python benchmarks/arrow_flight_benchmark.py --host localhost --port 39017 --user SYSTEM --password manager --num-documents 5000 --gpu-ids 0
    
    - name: Run multi-GPU benchmarks
      run: |
        python benchmarks/arrow_flight_benchmark.py --host localhost --port 39017 --user SYSTEM --password manager --num-documents 10000 --gpu-ids 0,1 --skip-traditional --skip-arrow-flight
    
    - name: Archive benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: gpu-benchmark-results
        path: benchmark_results/