name: Docker Build Cloud & Push

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag (optional)'
        required: false
        default: ''

jobs:
  docker_build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: cloud
          driver-opts: |
            image=moby/buildkit:v0.12.0
            memory=8gb
            cpu-quota=400000

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set variables for build
      - name: Set build variables
        id: vars
        run: |
          # Generate date-based tag
          DATE_TAG=$(date +%Y%m%d)
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV
          
          # Custom tag from workflow dispatch or use default CPU secure
          if [[ "${{ github.event.inputs.tag }}" != "" ]]; then
            CUSTOM_TAG="${{ github.event.inputs.tag }}"
          else
            CUSTOM_TAG="cpu-secure"
          fi
          echo "CUSTOM_TAG=${CUSTOM_TAG}" >> $GITHUB_ENV
          
          # Set repository
          echo "REPO=finsightintelligence/finsight_utils_langchain_hana" >> $GITHUB_ENV

      # Build and push the CPU image
      - name: Build and push CPU image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.secure
          push: true
          tags: |
            ${{ env.REPO }}:${{ env.CUSTOM_TAG }}
            ${{ env.REPO }}:${{ env.CUSTOM_TAG }}-${{ env.DATE_TAG }}
          platforms: linux/amd64
          build-args: |
            FORCE_CPU=1
            INSTALL_GPU=false
          cache-from: type=registry,ref=${{ env.REPO }}:buildcache
          cache-to: type=registry,ref=${{ env.REPO }}:buildcache,mode=max
          # Add resource limit parameters
          outputs: type=registry,compression=gzip,compression-level=9,force-compression=true

      # Optional: GPU version build
      - name: Build and push GPU image (optional)
        if: github.event.inputs.tag == 'gpu-secure' || github.event.inputs.tag == 'build-all'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.secure
          push: true
          tags: |
            ${{ env.REPO }}:gpu-secure
            ${{ env.REPO }}:gpu-secure-${{ env.DATE_TAG }}
          platforms: linux/amd64
          build-args: |
            FORCE_CPU=0
            INSTALL_GPU=true
          cache-from: type=registry,ref=${{ env.REPO }}:gpu-buildcache
          cache-to: type=registry,ref=${{ env.REPO }}:gpu-buildcache,mode=max
          outputs: type=registry,compression=gzip,compression-level=9,force-compression=true