name: Publish to NVIDIA NGC

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (default: from VERSION file)'
        required: false
        default: ''

jobs:
  publish-to-ngc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NGC CLI
        run: |
          wget -O ngccli.zip https://ngc.nvidia.com/downloads/ngccli_linux.zip
          unzip -o ngccli.zip && chmod u+x ngc-cli/ngc
          echo "$(pwd)/ngc-cli" >> $GITHUB_PATH

      - name: Login to NGC
        run: |
          mkdir -p ~/.ngc
          echo "${{ secrets.NGC_API_KEY }}" > ~/.ngc/config
          ngc config set

      - name: Get version
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          elif [ -f "VERSION" ]; then
            echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          else
            echo "VERSION=$(grep -m 1 version pyproject.toml | cut -d '\"' -f 2)" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to NGC
        env:
          NGC_ORG: ${{ secrets.NGC_ORG }}
          NGC_TEAM: ${{ secrets.NGC_TEAM }}
        run: |
          ./scripts/publish_to_ngc.sh ${{ env.VERSION }}

      - name: Verify NGC publication
        run: |
          ngc registry image list ${{ secrets.NGC_ORG }}/${{ secrets.NGC_TEAM }}/langchain-hana-gpu:${{ env.VERSION }}